name: CI VSCODE
on:
  push:
jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:trusty
    steps:
    - uses: actions/checkout@v2
    - name: Install vscode
      run: |
        apt-get update
        apt-get clean
        apt-get install -y wget
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
        install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
        sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
        apt-get install -y apt-transport-https
        apt-get update
        apt-get install -y code
